spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"
  session:
    timeout: 60m
    redis:
      namespace: "spring:session:management"
  data:
    redis:
      port: 6379

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only

jwt:
  public-key: cert/public_key.pem

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  # Static resources reloading during development
  web:
    resources:
      static-locations: file:src/main/resources/static/
  data:
    redis:
      host: localhost
      database: 2

account-registry:
  url: http://localhost:9050

device-registry:
  url: http://localhost:9010

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: Redis
      database: 2

account-registry:
  url: http://AccountRegistry:8080

device-registry:
  url: http://DeviceRegistry:8080

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
