spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"
  session:
    timeout: 60m
    redis:
      namespace: "spring:session:management"
  data:
    redis:
      port: 6379
      database: 2

server:
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
  ssl:
    key-store: classpath:cert/keystore.p12
    key-store-type: PKCS12

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only

jwt:
  public-key: cert/public_key.pem

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  # Static resources reloading during development
  web:
    resources:
      static-locations: file:src/main/resources/static/
  data:
    redis:
      host: localhost

server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
  ssl:
    enabled: false

account-registry:
  url: http://localhost:9050

device-registry:
  url: http://localhost:9010

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: Redis

server:
  error:
    include-message: always
  port: 8443
  ssl:
    enabled: true
    key-store-password: password

account-registry:
  url: http://AccountRegistry:8080

device-registry:
  url: http://DeviceRegistry:8080

---
##############################
### Kubernetes environment ###
##############################
spring:
  config:
    activate:
      on-profile: kubernetes
  data:
    redis:
      host: dependency-redis-master

server:
  port: 8443
  ssl:
    enabled: true

account-registry:
  url: http://account-register

device-registry:
  url: http://device-register
